import { CLIENT_SESSIONS_VIEW_SQL } from '@/lib/call-sessions';

export const NEON_SCHEMA_STATEMENTS = [
  `create table if not exists public.profiles (
    id uuid primary key,
    email text not null unique,
    full_name text,
    role text not null default 'client' check (role in ('client', 'coach', 'admin')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`,
  `create table if not exists public.coaches (
    id uuid primary key default gen_random_uuid(),
    profile_id uuid unique,
    email text not null unique,
    full_name text not null,
    fathom_source_key text,
    calendar_source_key text,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`,
  `create table if not exists public.clients (
    id uuid primary key default gen_random_uuid(),
    profile_id uuid unique,
    email text unique,
    full_name text not null,
    status text not null default 'active' check (status in ('active', 'inactive', 'extension')),
    drive_folder_url text,
    drive_folder_id text,
    first_call_id uuid,
    context_summary text,
    context_source_call_id uuid,
    context_generated_at timestamptz,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    desired_salary_range text,
    desired_salary_range_generated_at timestamptz,
    start_date date,
    end_date date
  )`,
  `create table if not exists public.coach_client_assignments (
    id uuid primary key default gen_random_uuid(),
    coach_id uuid not null references public.coaches(id) on delete cascade,
    client_id uuid not null references public.clients(id) on delete cascade,
    is_primary boolean not null default true,
    starts_on date,
    ends_on date,
    created_at timestamptz not null default now(),
    unique (coach_id, client_id)
  )`,
  `create table if not exists public.calls (
    id uuid primary key default gen_random_uuid(),
    client_id uuid references public.clients(id) on delete set null,
    coach_id uuid references public.coaches(id) on delete set null,
    source text not null default 'fathom' check (source in ('fathom', 'manual', 'calendar')),
    fathom_call_id text unique,
    title text,
    started_at timestamptz,
    duration_seconds integer,
    summary text,
    next_steps text,
    recording_url text,
    share_url text,
    calendar_event_id uuid,
    raw_metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    display_title text,
    display_title_generated_at timestamptz
  )`,
  `create table if not exists public.call_participants (
    id uuid primary key default gen_random_uuid(),
    call_id uuid not null references public.calls(id) on delete cascade,
    email text,
    name text,
    role_hint text,
    created_at timestamptz not null default now(),
    unique (call_id, email)
  )`,
  `create table if not exists public.calendar_events (
    id uuid primary key default gen_random_uuid(),
    coach_id uuid references public.coaches(id) on delete set null,
    client_id uuid references public.clients(id) on delete set null,
    google_event_id text not null unique,
    google_calendar_id text,
    title text,
    description text,
    starts_at timestamptz not null,
    ends_at timestamptz,
    attendee_emails text[] not null default '{}',
    status text not null default 'scheduled' check (status in ('scheduled', 'cancelled', 'completed', 'ignored')),
    matched_call_id uuid references public.calls(id) on delete set null,
    ignored_reason text,
    raw_metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`,
  `create table if not exists public.client_files (
    id uuid primary key default gen_random_uuid(),
    client_id uuid not null references public.clients(id) on delete cascade,
    google_file_id text unique,
    name text not null,
    mime_type text,
    url text not null,
    parent_folder_id text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`,
  `create table if not exists public.sync_runs (
    id uuid primary key default gen_random_uuid(),
    source text not null,
    source_key text,
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    status text not null default 'running',
    records_seen integer not null default 0,
    records_inserted integer not null default 0,
    records_updated integer not null default 0,
    error_message text,
    metadata jsonb not null default '{}'::jsonb
  )`,
  `create index if not exists assignments_coach_id_idx on public.coach_client_assignments (coach_id)`,
  `create index if not exists assignments_client_id_idx on public.coach_client_assignments (client_id)`,
  `create index if not exists calls_client_started_idx on public.calls (client_id, started_at desc)`,
  `create index if not exists calls_coach_started_idx on public.calls (coach_id, started_at desc)`,
  `create index if not exists call_participants_call_id_idx on public.call_participants (call_id)`,
  `create index if not exists calendar_events_client_starts_idx on public.calendar_events (client_id, starts_at desc)`,
  `create index if not exists calendar_events_coach_starts_idx on public.calendar_events (coach_id, starts_at desc)`,
  `create index if not exists client_files_client_id_idx on public.client_files (client_id)`,
  CLIENT_SESSIONS_VIEW_SQL,
] as const;
